### PR TITLE
XEP-0323, XEP-0324, XEP-0325: XML Example Corrections

### PR DESCRIPTION
**Pull request by PeterWaher**
Made corrections to XML in examples related to XEP-0323, XEP-0324 & XEP-0325.

### CODE REVIEW

**Comment by SamWhited** [comment]
This PR appears to modify the logo PDF and turn it into an invalid document.

Also, generally speaking, single self-contained commits are easier to review and get merged. I'm not sure if we have any policy on this though (eg. is it up to the editors to sort it out, or should large sprawling changes over many documents be rejected?)

**Comment by SamWhited** [comment]
@PeterWaher Any interest in cleaning this PR up and splitting it out into individual changes? If not I'm going to close this here as I attempt to clean up the remaining issues. Thanks!

**Comment by Kev** [comment]
On 17 May 2016, at 15:22, Sam Whited <notifications@github.com> wrote:
>  I'm not sure if we have any policy on this though (eg. is it up to the editors to sort it out, or should large sprawling changes over many documents be rejected?)

Editor’s discretion, I think.

/K

**Comment by SamWhited** [comment]
Since no one seems interested in merging this, I'm going to reject the change. In future, we may make it an "official" policy to keep pull requests small and local to one XEP unless special circumstances exist.

Feel free to resubmit this as several PRs, and thanks again for working on it.

(also, other editors, feel free to cherry pick these if you want; obviously I don't want to stop you merging if you want to spend the time on it)

**Pull request closed without merging**
