### PR TITLE
XEP-0340: Editorial changes, fixing syntax highlighting in examples

### PR DESCRIPTION
**Pull request by linkmauve**

### CODE REVIEW

**Comment by SamWhited** [comment]
Recently someone told me they didn't like the idea of using comments in examples, even for illustration; I'm not really sure what we should od about this now.

I also don't think this needs a version bump, it doesn't actually affect the output text in any meaningful way (it's more like a formatting change).

**Comment by linkmauve** [comment]
What were the arguments against?  In this case the SEND and RECV tags don’t add much information so I wouldn’t be against removing them altogether.  Another option would be to put them in the caption, encoding that in the XEP itself.

Btw I played with the idea of generating the examples directly from the XML, avoiding any potential not-well-formed issue, but my XSLT-fu is still way too weak.

**Comment by SamWhited** [comment]
> What were the arguments against?

I'm not sure; might be worth a mailing list thread.

**Comment by SamWhited** [comment]
Closing this for now since there's a conflict; thanks for the change though. I'll ask around and come up with a definitive way to format examples like this.

**Pull request closed without merging**
