### PR TITLE
XEP-0384: Introduce ODR, improve specification

### PR DESCRIPTION
**Pull request by strb**
This new version of the specification introduces the OMEMO Double
Ratchet. We now use our own, new wire format, making the protocol
independent from third parties.

This revision also improves the general quality of the specification
by describing behaviors in more detail and using terminology more
consistently.

### CODE REVIEW

**Comment by mnemonicflow** [comment]
Why the [implementation notes](https://cdn.rawgit.com/mnemonicflow/6fa778086b4fcadafe57118f79b84c43/raw/b13faa72055c5dc2ce1e13068a3adc6a82d83de6/xep-0384.html#impl) now have a focus towards using Signal implementations?

I see that the current version (v0.2) of this XEP has removed all references to Olm, which were present in the [0.0.2 version](https://github.com/xsf/xeps/commit/ac8cf918ee7427133b50cebd692c62dfb3ad175c)

As Olm implements the same Double Ratchet algorithm, albeit with some differences, I think it matches the requirements for the "OMEMO Double Ratchet (ODR)" and can be used instead of Signal. Right?

I still haven't found a non GPL implementation for the Signal protocol, are there any?
And I'm especially interested to have a non Signal based implementation because if someone is looking into integrating XMPP with OMEMO encryption in a mobile closed source app, for example by using [Smack Java library](https://github.com/vanitasvitae/smack-omemo) on Android or [XMPPFramework](https://github.com/robbiehanson/XMPPFramework) on iOS, they cannot do so using Signal, due to its licensing.
Because Olm is licensed under Apache License 2.0 it can be used in commercial applications.

Related: https://github.com/igniterealtime/Smack/pull/117#issuecomment-290413532

**Comment by Flowdalic** [comment]
> if someone is looking into integrating XMPP with OMEMO encryption in a mobile closed source app, for example by using Smack Java library on Android ... they cannot do so using Signal, due to its licensing

That's not true. The only limitation is that your IM app needs to be GPL(v3) compatible licensed if you want to use libsignal-protocol-java. See https://github.com/igniterealtime/Smack/wiki/OMEMO-libsignal-LIcensing-Situation

**Comment by Flowdalic** [comment]
> Because Olm is licensed under Apache License 2.0 it can be used in commercial applications.

You can use libsignal-protocol-java / smack-omemo-signal in commercial applications too.

**Comment by mnemonicflow** [comment]
@Flowdalic Without releasing the source code of the application and without paying moxie 2 million USD?

**Comment by mnemonicflow** [comment]
What I understand by reading the spec changes proposed in this PR is that there are only two possibilities for using OMEMO in a closed source app from a client side XMPP library (Smack, XMPPFramework, etc.) without releasing the source code of the app:
1. Create a non-GPL conforming XMPP OMEMO XEP implementation for the Signal protocol specifications:
   - The Double Ratchet Algorithm 
   - The X3DH Key Agreement Protocol 
   - The XEdDSA and VXEdDSA Signature Schemes 
2. Create a non-GPL non conforming XMPP OMEMO XEP implementation that uses Olm or something else
Correct?

**Comment by ara4n** [comment]
See https://mail.jabber.org/pipermail/standards/2017-March/032551.html for some attempts at clarity from the Olm side.

**Comment by remko** [comment]
As a result of the discussion in that thread, I also suggest this PR be moved back to Olm. 

This would also solve the underspecification of some parts in this PR that result from defining our own Ratchet (e.g. header serialization format for authentication).

Some of the changes in this PR are still valid, though (e.g. more consistent tag names, the encryption scheme for the payload (which is also consistent with Olm)).

**Comment by remko** [comment]
Added the described changes in #463

**Comment by horazont** [comment]
@strb Can you please [sign the CLA via the CLA-bot thing](https://cla-assistant.io/xsf/xeps?pullRequest=460)?

**Comment by horazont** [comment]
@strb Am I right in my assumption that this PR can be closed since #482 has been merged?

**Comment by horazont** [comment]
I am closing this for inactivity. Feel free to reopen.

**Pull request closed without merging**
