### PR TITLE
Mix (XEP-0369) to 0.8.1

### PR DESCRIPTION
**Pull request by stevekille**
Editorial Updates;
      Clarify Access to MAM history, prior to user joining channel;
      Add option for user to join without presence;
      Check invitee supports MIX

### CODE REVIEW

**Comment by SamWhited** [comment]
I think I got this rebased and merged properly; sorry for the delay.

Future work should probably be based on whatever the latest master version is (although huge breaking changes like the one that caused these issues should be pretty rare; I may look into adding a diff script to avoid this later).

**Comment by stevekille** [comment]
I’ll rebase.    Might have a go at the next set of changes on my plane ride home later today

 

 

Steve

**Comment by SamWhited** [comment]
> I’ll rebase. Might have a go at the next set of changes on my plane ride home later today

Thanks! Probably best to base your new changes off the master branch (and then create a new branch when you're ready to submit a PR); I think rebasing and misunderstandings about how rebasing works might have been what caused this problem. In general (at least the way I tend to handle repos), you probably don't want to rebase ever, just create new branches off master to work from (I'll rebase if necessary). But whatever works for you; let me know if you need a hand with it.

**Comment by stevekille** [comment]
Thanks. That is what I've done and generally how I work. My master is rebased  
on xsf/master and I'll make a new branch when I start editing

Steve

**Comment by SamWhited** [comment]
> My master is rebased on xsf/master

I'm not sure if this is a terminology mixup, or if something bad is actually happening here, but you should never need to rebase master on top o xsf/master; they should be the exact same thing :)

**Comment by stevekille** [comment]
I do fetch remote xsf/xeps. And then rebase xsf/xeps so I am pointing to the  
head.  Is this wrong g?


S

**Comment by Kev** [comment]
On 23 Feb 2017, at 15:58, Sam Whited <notifications@github.com> wrote:
> 
> My master is rebased on xsf/master
> 
> I'm not sure if this is a terminology mixup, or if something bad is actually happening here, but you should never need to rebase master on top o xsf/master; they should be the exact same thing :)

It’s neither. Rebase is just one of the possible mechanisms for doing a fast-forward of master to xsf/master.

/K

**Comment by SamWhited** [comment]
> I do fetch remote xsf/xeps. And then rebase xsf/xeps so I am pointing to the head. Is this wrong g?

Not exactly wrong, but it means if you have any commits in your master branch that don't exist on xsf/master, they will continue to exist and will end up in your new branches and pull requests, which may or may not be what you want.

If you just want your master branch to look exactly like xsf/master (this will remove any commits you have on the branch that aren't saved elsewhere), you probably want to do something like:

```
git fetch xsf
git checkout master
git reset --hard xsf/master
```

**Comment by Kev** [comment]
On 23 Feb 2017, at 16:08, Sam Whited <notifications@github.com> wrote:
> 
> I do fetch remote xsf/xeps. And then rebase xsf/xeps so I am pointing to the head. Is this wrong g?
> 
> Not exactly wrong, but it means if you have any commits in your master branch that don't exist on xsf/master, they will continue to exist and will end up in your new branches and pull requests, which may or may not be what you want.
> 
> If you just want your master branch to look exactly like xsf/master (this will remove any commits you have on the branch that aren't saved elsewhere), you probably want to do something like:
> 
> git fetch xsf
> git checkout master
> git reset --hard xsf/master

I think that recommending anyone start doing `reset —hard` without explaining what it means is a Very Bad Idea. Rebase is fine for what Steve’s doing, where he isn’t committing anything on master.

/K

**Comment by SamWhited** [comment]
> Rebase is fine for what Steve’s doing, where he isn’t committing anything on master.

Unless it's how the old commits that were dropped got brought forwards (which it may or may not be).

**Pull request closed without merging**
