### PR TITLE
XEP-0384: Receiving PreKeyMessages should trigger signed prekey rotation

### PR DESCRIPTION
**Pull request by vanitasvitae**
See the [protocol audit](https://conversations.im/omemo/audit.pdf) chapter 4:
```
The  lifetime  of  (signed)  prekeys  should  be  mentioned  in  the  standard.   Signed  prekeys
should be changed regularly in order to achieve forward secrecy.  This should at least be done
after every time the user receives a PreKeySignalMessage that uses the latest signed prekey,
but  it  can  be  done  more  often  (based  on  time)  to  ensure  the  forward  secrecy  of  dropped
messages.
```

### CODE REVIEW

**Comment by jcbrand** [comment]
@strb Would you mind reviewing this PR?

**Comment by vanitasvitae** [comment]
ping @strb

**Comment by strb** [comment]
I apologize for the delay, this somehow slipped through the cracks.

This change is good.

The only thing that bothers me a little is the change to the acknowledgements. I'm not sure if this is just "how it's done", but it feels a bit weird to me, almost like having words put into my mouth. Don't get me wrong, I'm not at all against contributors being acknowledged properly. I'm very grateful that people are interested in OMEMO and doing work on it. But I'd prefer if those were listed separately. The list of names that was added to in this revision was not really a list of contributors, but a list of people whose input I had specifically sought out when drafting the initial version of the standard, though I can see how it'd seem that way, so I don't blame you for doing it like this.

I'd be in favor of just adding a separate paragraph that says something like "Thanks to X, Y, Z for their contributions to the standard" or something like that. This way, in the future, further contributors would then have an obvious place to add themselves to if they want. (e.g. @linkmauve in #686) Not sure how this is handled in other XEPs though?

The revision entry w/ version bump is missing, but since this, #686 and #707 are independent changes the ordering doesn't matter, so this can be resolved in any order.

**Comment by vanitasvitae** [comment]
> But I'd prefer if those were listed separately.

Sure, I can fix that :)

**Comment by vanitasvitae** [comment]
I reverted the changes to the acknowledgements for now.

**Comment by horazont** [comment]
@strb Please check whether the PR is good now.

**Pull request closed without merging**
