### PR TITLE
XEP-0227: New revision 1.1

### PR DESCRIPTION
**Pull request by mwild1**
- Discourage inclusion of plaintext passwords
- Document a format for including SCRAM data
- Define data formats for PEP and MAM data

### CODE REVIEW

**Comment by stpeter** [comment]
LGTM

**Comment by mwild1** [comment]
Pushed a new commit that addresses feedback from @dwd.

**Comment by mwild1** [comment]
Based on list feedback I intend to make some small additions to the described format of PEP/pubsub nodes, to allow inclusion of affiliations and explicit subscriptions. I've therefore marked the PR as draft again.

**Comment by mwild1** [comment]
Updated [per list feedback](https://mail.jabber.org/pipermail/standards/2021-July/038423.html) to address the outstanding concerns. Removing draft tag.

**Pull request merged**
