### PR TITLE
XEP-0272: Update to adjust for current XMPP protocols

### PR DESCRIPTION
**Pull request by mar-v-in**
- Send Jingle IQs to real JID
- Define how to use with XEP-0482
- Adjust namespace

### CODE REVIEW

**Comment by melvo** [comment]
This PR depends currently on #1155 because of the section `Call Invite Messages`.

**Comment by edhelas** [comment]
A little bump on that one as I'm planning to work on Muji soon in Movim

**Comment by mar-v-in** [comment]
@iNPUTmice I think this one is also ready for merge. You got the confirmation of the author forwarded

**Comment by iNPUTmice** [comment]
Can you add yourself as an author please?

**Comment by mar-v-in** [comment]
I already did, it's the `&larma;` line before the revision block :)

**Pull request merged**
