### PR TITLE
Add explicit reject by responding to sender with reject message

### PR DESCRIPTION
**Pull request by xdumaine**
@fippo

### CODE REVIEW

**Comment by fippo** [comment]
LGTM, @stpeter?

**Comment by stpeter** [comment]
+1 - thanks for the Twitter poke (not that I pay close attention to Twitter these days, but it worked this time!)

**Comment by xdumaine** [comment]
@fippo what's next to merge this? Also, should I be a member of this org now?

**Comment by fippo** [comment]
waiting for someone from the editors team to find time ;-)

**Comment by SamWhited** [comment]
Sorry, I still don't know how to regenerate things on the server so I'm hesitant to merge things since I won't be able to make sure it doesn't cause problems later. @ashward can you please write up instructions for this somewhere? Even if it's just sending me a quick "use this venv in this directory, and run this script" it would be super helpful.

**Comment by ashward** [comment]
Thanks @SamWhited. I really need to sort out those instructions! If you have ten minutes I can talk you through updating a XEP. First thing to do is get this merged to master with a new version number (0.2?).

**Comment by SamWhited** [comment]
Merged as 23e20e22b89b051f5b8f8de2a6567c3d63f2a96b

**Pull request closed without merging**
