### PR TITLE
Move XEP-0352 (CSI) to Last Call (Proposed)

### PR DESCRIPTION
**Pull request by SamWhited**
See discussion on the mailing list.

### CODE REVIEW

**Comment by linuxwolf** [comment]
As per XEP-0001, this requires a decision by the XMPP Council.  Consider it added to their next agenda.

**Comment by SamWhited** [comment]
:+1: After all this "fun" discussion on the MUC/ML, I can hardly wait :)

**Comment by SamWhited** [comment]
Oops, not sure why I closed this.

**Comment by linuxwolf** [comment]
Need to add a <lastcall/> element, with the date LC ends; it's chosen by the XEP Editor.  This Editor says that should be 2015-08-25.

Adding as I merge it (which I'm in the middle of now).

**Comment by linuxwolf** [comment]
#49 to track council.

**Comment by linuxwolf** [comment]
Merged as f1d3d763f36532d7c3c2825a30a1d699788e48bc.

LC date is 2015-09-07

**Pull request closed without merging**
