### PR TITLE
Overhaul SCRAM Upgrade ProtoXEP to include definition of SASL2 upgrade tasks

### PR DESCRIPTION
**Pull request by tmolitor-stud-tu**
Current rendering: https://dyn.eightysoft.de/final/xep-scram-upgrade.html#protocol

### CODE REVIEW

**Comment by horazont** [comment]
Uuuuuuh you're changing a protoxep which is being voted on in a way which causes merge conflicts. 

Please provide links to list discussion which explains why.

**Comment by tmolitor-stud-tu** [comment]
@horazont as far as I know, voting was postponed because of it's SASL2 dependency.

The update is because Dave and MattJ wanted to move the update tasks to it's own xep.
They argued that such upgrade tasks are merely a single usecase for SASL2 tasks and don't belong into SASL2 directly.

Dave said so in the pull request review on github (I've tagged you there so that you can find it).
When Dave did not answer for a longer period, I discussed with @mwild1 how to proceed and he said, that he would like to split that out, too.
That's why I did it the way it is now.

**Comment by tmolitor-stud-tu** [comment]
I did a rebase on master which should resolve all merge conflicts. I've also fixed some bugs in the examples and changed the structure for better readability.

**Comment by tmolitor-stud-tu** [comment]
This is related to #1214 and should be merged/voted on/published after #1214 was merged/published...

It contains stuff that was originally part of the XEP-0388 overhaul but was since split out on @dwd 's request.

**Comment by Neustradamus** [comment]
To follow

**Comment by Kev** [comment]
This doesn't pass CI.

**Comment by tmolitor-stud-tu** [comment]
Kev: fixed

**Comment by tmolitor-stud-tu** [comment]
@Kev fixed now :)

**Pull request merged**
