### PR TITLE
Remove old shtml files

### LINKED ISSUE #295: Audit / remove old HTML
There are several (S)HTML files scattered about the repo that can most likely be removed. The ones that provide redirects can be handled in the xsf/xmpp.org repo instead, or in the nginx config; either way they probably shouldn't be in the xeps repo.

### PR DESCRIPTION
**Pull request by SamWhited**
Fixes #295

### CODE REVIEW

**Comment by intosi** [comment]
Did you deliberately leave out submit.shtml?

**Comment by SamWhited** [comment]
I don't actually see a submit.shtml

**Comment by intosi** [comment]
Fair enough :)

**Comment by intosi** [comment]
Thanks!

**Pull request merged**
