### PR TITLE
XEP-0071: move to obsolete

### PR DESCRIPTION
**Pull request by SamWhited**
Per council vote.

### CODE REVIEW

**Comment by JerryJian** [comment]
Hi, where can I find the reason why xep-0071 is obsoleted?
Do we have any replacement protocol of XHTML?
Thanks in advance.

**Comment by horazont** [comment]
@JerryJian The core reason is that it caused quite a few XSS vulnerabilities. There are lengthy threads on the standars mailing list:

* starting with [Security issues with XHTML-IM (again)](https://mail.jabber.org/pipermail/standards/2017-October/033546.html)
* some discussion on replacement in [Rich(er) text in IM vs XHTML docs](https://mail.jabber.org/pipermail/standards/2017-October/033596.html)
* collection of replacement requirements in [Formatting Use Cases](https://mail.jabber.org/pipermail/standards/2017-October/033702.html)

And much more. I recommend you to browse the archives if you really want to get the whole picture. The XMPP standards community has discussed this at length and the final ruling of the council is in the respective meeting minutes: [Council Minutes 2018-02-14](https://mail.jabber.org/pipermail/standards/2018-February/034302.html) and [MUC logs of the meeting](https://mail.jabber.org/pipermail/standards/2018-February/034302.html).

---

As for an replacement, it depends on your use-case. There’s XEP-0393 (Message Styling) which should cover many IM use-cases. I started to work on XEP-0394 (Message Markup) which intends to do a bit more, with a more flexible approach. Note that I intend to overhaul XEP-0394 and I don’t know of any implementations.

**Comment by JerryJian** [comment]
Thank you, @horazont @SamWhited

**Comment by horazont** [comment]
Obsoletion was incorrect, has been rectified to Deprecation in 48593ca5b8659553c02ce7b9e12fa7660436d9bc.

**Pull request merged**
