### PR TITLE
XEP-0234: Use <hash-used/> to signify the hash function being used, instead of an (invalid) empty <hash/>

### PR DESCRIPTION
**Pull request by Ri0n**
Most likely smeone just forgot to update the exampe after introducing hash-used in this xep.

### CODE REVIEW

**Comment by horazont** [comment]
This is inconsistent. The text above the example explicitly talks about an empty ``<hash/>`` element. This, of course, is in conflict with what XEP-0300 says. So please update the PR so that it also fixes the text above the example.

**Comment by horazont** [comment]
@stpeter @legastero Please review.

This changes the effective Schema and might require a namespace bump to fix, even though the previous text was (I think) invalid use of XEP-0300.

**Comment by horazont** [comment]
@Ri0n As you can see, I notified the authors for feedback. This may take a few days.

**Comment by Ri0n** [comment]
Thanks

**Comment by stpeter** [comment]
Hmm, this does seem to be an error in the text and examples, and would also necessitate a change to the schema (which we should include in this PR). As to whether this requires a namespace bump, I leave that to the Council.

**Comment by horazont** [comment]
@stpeter Thanks! I’ll try to squeeze this into today’s Council meeting.

@Ri0n Could you make the changes to the schema?

**Comment by Ri0n** [comment]
Added to schema. Not sure if it's correct.
By the way the XEP also notices hash-used can be used in <checksum>. I believe it's somewhat wrong. Checksum should always provide hash value.

**Comment by dwd** [comment]
(Passed Council, 2019-02-20)

**Pull request merged**
