### PR TITLE
XEP-0045: Business Rule for client-requested full resync

### PR DESCRIPTION
**Pull request by ge0rg**
As [discussed on the ML][0]: When a client re-joins a MUC where the MUC service did not notice the client leaving, the client will end up with an incomplete list of participants and no room subject.

This patch adds a sentence to the business rules section that explicitly requires a MUC service to send a full sync whenever it receives a MUC join presence (as opposed to the old groupchat protocol).

In my eyes, this is only a clarification of the existing standard definition, so we do not need to bump the version.

Georg

[0]: http://mail.jabber.org/pipermail/standards/2016-June/031180.html

### CODE REVIEW

**Comment by tfar** [comment]
Seems on this is mostly a clarification of behaviour already described and implementers on the mailing list all say this reflects current implementation  behaviour. I don't find a mention in http://xmpp.org/extensions/xep-0001.html that this would require any action from the council. The change looks okay to me. Would be nice if someone with merge powers could merge this.

**Comment by SamWhited** [comment]
@ge0rg Any chance you could add a revision block at the top with a minor version bump? Thanks.

**Comment by Flowdalic** [comment]
Council trello card: https://trello.com/c/wBfhDIMV

**Comment by stpeter** [comment]
Although this seems like a fine change, I'm still curious how this is currently handled in running code.

**Comment by stpeter** [comment]
I'm +1 on this, not having seen any concerns from implementers.

**Comment by Flowdalic** [comment]
Council voted all +1: https://trello.com/c/wBfhDIMV

**Pull request merged**
