### PR TITLE
XEP-0158: Use the correct FORM_TYPE for extended IBR, and use a proper MUC join as an example

### PR DESCRIPTION
**Pull request by linkmauve**
This was found while implementing IBR CAPTCHA in [Renga](https://github.com/HaikuArchives/Renga) at the [Stockholm sprint](https://wiki.xmpp.org/web/Sprints/2019_September_Stockholm).

### CODE REVIEW

**Comment by Ppjet6** [comment]
Merged as b107617. Thanks!

**Comment by zinid** [comment]
Well, putting 'jabber:iq:register' there is also wrong, because CAPTCHA related fields are not registered in its form type: https://xmpp.org/extensions/xep-0077.html#registrar-formtypes

**Comment by linkmauve** [comment]
https://xmpp.org/extensions/xep-0158.xml#registrar-formtypes-register is the process to add new fields to an existing FORM_TYPE’s registrar, you should be looking at the registrar instead of the original XEP (which shouldn’t get modified every time an extension adds something to its form).

**Comment by zinid** [comment]
@linkmauve well I think this is just plain wrong of course.

**Comment by linkmauve** [comment]
Well, according to [XEP-0001 §14](https://xmpp.org/extensions/xep-0001.xml#registrar), it definitely is the registrar’s function to register form fields, and in this case they have done so already: https://xmpp.org/registrar/formtypes.html#jabber:iq:register

**Pull request closed without merging**
