### PR TITLE
Add RFC 3629 to xep.ent and add travis config file

### PR DESCRIPTION
**Pull request by Flowdalic**
I suggest to enable Travis CI for xsf/xeps. It already shows that some XML entities used in the XEPs are not defined:

```text
xep-0155.xml:669: parser error : Entity 'xmppsipim' not defined
ing instant messaging flows to SIP, implementations SHOULD adhere to &xmppsipim;

xep-0166.xml:598: parser error : Entity 'xmppsipmedia' not defined
(SIP) and the ITU's H.323 protocol (see &H.323;); see for example &xmppsipmedia;

xep-0246.xml:45: parser error : Entity 'ice-tcp' not defined
 or XMPP itself (&xep0047;), or other future transport methods such as &ice-tcp;

xep-0260.xml:462: parser error : Entity 'ice-tcp' not defined
1;, however if other transport methods are defined in the future (e.g. &ice-tcp;

xep-0298.xml:90: parser error : Entity 'rfc4579' not defined
    in &rfc4579;</p>
                ^
xep-0298.xml:119: parser error : Entity 'rfc4579' not defined
        mechanisms such as &rfc4579; or &xep0272;</li>
```

After those are fixed, we should tighten the rules so that those errors cause the CI to fail.

### CODE REVIEW

**Comment by linuxwolf** [comment]
We can take the xep.ent update, but enabling Travis is a deeper discussion we still need to have.

**Comment by winfried** [comment]
Think this should be setup in joint cooperation between the editorial team and the infrastructure team. Already had in Brussels a little chat about it with Intosi.

**Comment by SamWhited** [comment]
Cherry picked the `xep.ent` changes as 54288764aff6edc0402df10946dd4c2fda8ba692. This PR is now just the Travis config.

**Comment by SamWhited** [comment]
Closing this PR since it's still multiple commits. Feel free to re-submit just the Travis change.

**Pull request closed without merging**
