### PR TITLE
XEP-0377: Add the XML Schema

### PR DESCRIPTION
**Pull request by linkmauve**
This has been tested with xmllint against every example in the XEP.

### CODE REVIEW

**Comment by Kev** [comment]
@linkmauve could you add a version block, please?
@SamWhited are you ok with this?

**Comment by linkmauve** [comment]
@Kev done.

**Comment by Kev** [comment]
Poking Sam out of band for the author check.

**Comment by Kev** [comment]
Sam (without reviewing the schema) is happy it is merged.

**Comment by linkmauve** [comment]
Hi, any news on that one?

**Pull request merged**
