### PR TITLE
XEP-0352: Explain how CSI is affected by in order processing

### PR DESCRIPTION
**Pull request by Flowdalic**
Following up on the productive discussion caused by #34, I now suggest the following change instead of #34. Hope that everyone agrees and is happy with out. If not, please raise your voice. :)

Clarify how the in order processing requirement (RFC 6120 § 10.1) affects CSI.

### CODE REVIEW

**Comment by fippo** [comment]
with a LC requested for CSI I'd prefer not to have any changes made to that until the LC is done. However, a branch tracking LC feedback and proposed changes would be good :+1:

**Comment by stpeter** [comment]
I will raise this issue on the list.

**Comment by Flowdalic** [comment]
> I will raise this issue on the list.

I couldn't find it raised on the list, so I commented on the LC thread.

**Comment by mwild1** [comment]
Just +1'd this in the LC thread on the list.

**Comment by linuxwolf** [comment]
Merged via PR #105.

We're trying to work out a flow to prevent problems with the published database.  This was the first experiment.

**Comment by linuxwolf** [comment]
Re-opening ... the experiment was a failure.  XEP-diff would not recognize the actual changes.

**Comment by linuxwolf** [comment]
Merged in with #107 and updated revision.

**Pull request closed without merging**
