### PR TITLE
XEP-0001: Release version 1.25.0

### PR DESCRIPTION
**Pull request by melvo**
Specify XEP versioning

### CODE REVIEW

**Comment by melvo** [comment]
@wurstsalat3000 @Echolon @Zash @Kev Here is the outcome of our discussion.

**Comment by horazont** [comment]
Is there a mailing list discussion on this? Because I have words to say on that and I'd like to put them in our standard venue instead of on github.

If there is a discussion, please link it here.

**Comment by Kev** [comment]
> Is there a mailing list discussion on this? Because I have words to say on that and I'd like to put them in our standard venue instead of on github.

No. There was a question in one of the MUCs in which I said (roughly) that major was for advancement, patch was for Editorial-only changes, and minor was for other changes. Which I believe to be correct, but I don't believe it needs this change to confirm that (the major bit is already documented elsewhere, and IIRC when we introduced patches for editorial changes a few years ago we decided that this was implicit because of the definition of maj.min).

**Comment by melvo** [comment]
@horazont The reason for specifying that topic was that @wurstsalat3000 wanted to create a list of XEPs a client, library or server implements and show a hint if the implemented version is not up-to-date. But such a hint should not be shown for different patch versions since they are only meant for editorial changes. The problem was that it was not clear and we could not find any document that specified it. I will sent a link to this PR to the corresponding mailing list.

**Comment by horazont** [comment]
I'm not sure what to do with this, the [list discussion](https://mail.jabber.org/pipermail/standards/2022-August/038940.html) was inconclusive to me.

While I agree that it'd be great to have a versioning scheme written down, as I mentioned on-list, that's not going to be fixed for existing documents and as others noted, that's not the only interoperability criterium there is, so it might not even solve the issue at hand.

Please reopen if you think differently or drive the mailing list discussion forward to a clear consensus.

**Pull request closed without merging**
