### PR TITLE
MIX (XEP-0369) update to 0.9.1

### PR DESCRIPTION
**Pull request by stevekille**
Editorial Changes (addressing comments  from Timothée Jaussoin)

### CODE REVIEW

**Comment by SamWhited** [comment]
Thanks Steve! Just FYI, since the website issues the other day the editor tooling is currently down, so I may not be able to process this for a while. I don't have an ETA, as I'm not sure if anyone is working on this or what's going to happen with the tooling. Will advise.

**Comment by stevekille** [comment]
Understood.   Sounds like it has been a perfect hell with the website

 

S

**Comment by SamWhited** [comment]
Merged; thanks @stevekille, sorry about the long delay.

**Comment by stevekille** [comment]
Thanks for sorting this

 

S

**Pull request merged**
