### PR TITLE
Add SIMS to inbox

### PR DESCRIPTION
**Pull request by tfar**
This ProtoXEP aims to provide a stateless and asynchronous
way to describe shared media and the ways to retrieve it.

### CODE REVIEW

**Comment by SamWhited** [comment]
```
$ xmllint --nonet --noout --noent --loaddtd --valid xep-sims.xml
xep-sims.xml:123: element p: validity error : Element ul is not declared in p list of possible children
  </ul></p>
           ^
```

**Comment by tfar** [comment]
would be great to add `xmllint` to the CI. Will fix the bug in ProtoXEP.

**Comment by SamWhited** [comment]
It is but it's using a ratcheting build so that it only picks up new errors. I seem to have forgotten to update the numer of "acceptable" (existing) errors. Doing that now.

**Comment by tfar** [comment]
Ah..ok. Fixed the issue raised by xmllint now.

**Comment by SamWhited** [comment]
IPR email sent. Awaiting author response.

**Comment by SamWhited** [comment]
Author response received.

**Comment by SamWhited** [comment]
Merged as 5f1a22c

**Pull request closed without merging**
