### PR TITLE
XEP-0198: Send 'a' element before stream closure

### PR DESCRIPTION
**Pull request by sco0ter**
Clients should add a delay element when resending stanzas, so that the
original send date is preserved.

### CODE REVIEW

**Comment by dwd** [comment]
These both look like sensible changes, but I'd like to run them past Council and the standards list first.

**Comment by sco0ter** [comment]
Ok, thanks! It's just something which I've noticed during client development.
Related mail: https://mail.jabber.org/pipermail/standards/2015-July/030088.html

**Comment by Flowdalic** [comment]
Created card for council: https://trello.com/c/fXsAbLzM

**Comment by stpeter** [comment]
+1 - this is a nice change. :-)

**Pull request merged**
