### PR TITLE
MUC Light XEP

### PR DESCRIPTION
**Pull request by fenek**
An attempt of creating MUC2 XEP. It was internally called "MUC Light" from the very beginning, so the name remained but I have nothing against calling it MUC2 eventually. :)

It's pretty much ready. I think XML Schema may probably need updating or rewriting.

### CODE REVIEW

**Comment by SamWhited** [comment]
Note that new submissions should be in the `inbox/` tree. Could you move this to `inbox/muc_light.xml` or something similar?

Also, if you're not familiar, there's another proposal being worked on called MIX: https://stpeter.im/files/mix.html Might be worth a read before the list discussion starts. Thanks!

**Comment by fenek** [comment]
Hi Sam,

Sorry, I have somehow missed the information about putting new file in `inbox/`. It's fixed now.

I've seen this proposal under name `MUC2` posted somewhere on mailing list but I would still like to submit my XEP, as it solves the same problem with different approach (e.g. avoids PubSub and presences).

**Comment by linuxwolf** [comment]
Accepting XEPs will be paused temporarily until the XMPP Council and Board elections complete, which is about another week.

**Comment by linuxwolf** [comment]
IPR questionnaire sent < http://mail.jabber.org/pipermail/editor/2015-December/000429.html >

**Comment by linuxwolf** [comment]
Merged collapsed as eca705e.

**Comment by linuxwolf** [comment]
Corrected revision committed in 12139d5.

**Comment by bilalrotan** [comment]
can anyone help me in this issue please 

https://github.com/esl/MongooseIM/issues/1972

**Pull request closed without merging**
