### PR TITLE
Update XEP-0300 to current standards; adding SHA-3 and BLAKE2

### PR DESCRIPTION
**Pull request by tfar**

### CODE REVIEW

**Comment by SamWhited** [comment]
Author emails sent. Sorry for the delay. I'll get this merged and the XEP back to the experimental state as soon as they get back to me.

**Comment by stpeter** [comment]
I think there's a word missing here? "The pre-image resistance property of the MD5 algorithm is considered since 2009" ... is considered what?

Also here: "The BLAKE2 was designed" ... algorithm or family of algorithms?

s/particula algorithm/particular algorithm/

The rest looks good - thanks for the PR!

**Comment by tfar** [comment]
Thanks @stpeter . Think I've addressed all the issues you mentioned in the latest  update.

**Comment by SamWhited** [comment]
Received the go ahead from PSA in the council MUC. This PR is now ready for merge.

**Comment by SamWhited** [comment]
Note to whomever merges this: Please ensure the status is "Last Call" per the council vote on 2016-08-03: http://logs.xmpp.org/council/2016-08-03#15:16:10

**Pull request merged**
