### PR TITLE
XEP-0425: Remove duplicate '.'

### PR DESCRIPTION
**Pull request by vanitasvitae**

### CODE REVIEW

**Comment by vanitasvitae** [comment]
Why does this change need a version block? Isn't it purely editorial?

**Comment by Ppjet6** [comment]
We increase the patch version on editorial changes.

**Comment by vanitasvitae** [comment]
Ah okay.

**Comment by horazont** [comment]
Huh. Github doesn’t see it, probably because I did something stupid. Closing (it is merged).

**Pull request closed without merging**
