### PR TITLE
XEP-0401: Use Data Form for IBR and fix error stanzas

### PR DESCRIPTION
**Pull request by af8a524db1**
* Use Data Form for In-Band Registration as required by XEP-0077
 * Fix error stanzas as required by RFC 6120 § 8.3.2
 * Change error of "invalid-token" error to "modify"

### CODE REVIEW

**Comment by Flowdalic** [comment]
Doesn't this require a namespace bump since the registration fields are now returned in a form?

**Comment by dwd** [comment]
That'd be my thought too. (But note it's the Editor's role to do that as needed).

Also, I'd highly recommend raising this change on the mailing list, if only to get some conversation going about the spec.

**Comment by horazont** [comment]
Removing ready to merge since @ge0rg has feedback he wants to send.

**Comment by ge0rg** [comment]
Pinged the list at https://mail.jabber.org/pipermail/standards/2018-February/034323.html

**Comment by horazont** [comment]
Discussion thread is https://mail.jabber.org/pipermail/standards/2018-February/034315.html

**Pull request merged**
