### PR TITLE
Add <uri /> to XEP-0358

### PR DESCRIPTION
**Pull request by legastero**
Allows including a link to the advertised content or alternatives. For example, an advertisement for a  RTP video stream could include a link to a web page with a video player for the stream.

@stpeter

### CODE REVIEW

**Comment by linuxwolf** [comment]
Merged as b6199650d63a1d5341dab50fee80f50d175588c3.

**Comment by SamWhited** [comment]
/me twitches at the history that's being destroyed by all these commits. I really don't understand why we're losing it just to chagne the commit message. A normal merge would work just fine.

**Comment by linuxwolf** [comment]
This is the model the editor team agreed to.

You are of course open to filing an complaint with the XSF Board.

**Comment by SamWhited** [comment]
Being discussed in the XSF room now. This is nuts, you could merge, you could rebase and do a fast-forward merge, you could cherry-pick and push, you could ask them to squash and then merge that if they've got too many commits (or you could squash and maintain their authorship)... Git provides a lot of valid workflows, copy/pasting files around (or ammending the authors commits and destroying the hihstory) and re-pushing is not one of them. You're losing a lot of history here, which is going to make it difficult to find things in the future when you eg. want to know who made that one patch to that one XEP that one time, and instead all you can see is that @linuxwolf authored the entire file.

**Comment by SamWhited** [comment]
Oops, yup, my mistake. The GitHub UI wes misleading; after observing the history, it looks like you're doing exactly what I was thinking you should be doing. Apologies.

**Pull request closed without merging**
