### PR TITLE
XEP-0363: Fix XML in the examples

### PR DESCRIPTION
**Pull request by xnyhps**
Almost all examples were not valid XML, this fixes that.

### CODE REVIEW

**Comment by xnyhps** [comment]
Example 2 is also missing a `type='result'`.

**Comment by ashward** [comment]
This looks like it could reasonably be categorised as editorial changes to me (rather than requiring author approval)? @linuxwolf

**Comment by ashward** [comment]
```
From: Daniel Gultsch <daniel@gultsch.de>
Date: Tue, Dec 15, 2015 at 11:39 AM
Subject: Re: Updated Received for XEP-0363
To: Sam Whited <sam@samwhited.com>


Hi,

yes thats fine. I accept the changes.

cheers
Daniel
```

**Comment by SamWhited** [comment]
Squashed and merged.

**Pull request closed without merging**
