### PR TITLE
XEP-0384: Make examples use item id='current'

### PR DESCRIPTION
**Pull request by linkmauve**
This makes it respect XEP-0060 §12.20 on singleton nodes.

### CODE REVIEW

**Comment by horazont** [comment]
I don’t think this passes as patch level version bump. Also, @iNPUTmice please ack.

**Comment by horazont** [comment]
Also, on a personal note, I’d appreciate if there was a paragraph giving a rationale for ``id="current"`` (by referencing the XEP-0060 wording on singleton nodes).

**Comment by goffi-contrib** [comment]
A paragraph explaining that `current` **SHOULD** be used for `id` would be necessary IMHO.
I would use **SHOULD** instead of **MUST** to avoid namespace bump.

**Comment by Flowdalic** [comment]
@goffi-contrib isn't that what

        <p>NOTE: as per <link url='https://xmpp.org/extensions/xep-0060.html#impl-singleton'><cite>XEP-0060</cite> §12.20</link>, it is RECOMMENDED for the publisher to specify an ItemID of "current" to ensure that the publication of a new item will overwrite the existing item.</p>

adds (Note that 'RECOMMENDED' equals 'SHOULD')?

**Comment by goffi-contrib** [comment]
@Flowdalic yes it is, it seems that I've missed it :)

**Comment by jcbrand** [comment]
@strb We need you as author to review this PR please.

**Comment by strb** [comment]
I apologize for the delay, this somehow slipped through the cracks.

The change looks good to me. It doesn't really change the mechanics of anything, just makes things more explicit, so the patch-level change thing is fine IMO.

**Pull request merged**
