### PR TITLE
XEP-0280: Clarify the Carbons state after SM resumption.

### PR DESCRIPTION
**Pull request by Flowdalic**
And since this needs a namespace bump of carbons anyway, also remove
the &lt;private/&gt; element in favor of &lt;no-copy/&gt;.

### CODE REVIEW

**Comment by ge0rg** [comment]
Just a small note that this all-in-one commit will make #434 fail, at least because the other PR also removes the <private/> element.

**Comment by Ppjet6** [comment]
What's the state of this?

**Comment by ge0rg** [comment]
Looks like back in 2017, council [informally decided](https://logs.xmpp.org/council/2017-03-08#2017-03-08-70a456d72a6dc76f) that the clarification doesn't need a namespace bump.

**Comment by Ppjet6** [comment]
Ok so, we can remove the namespace bump and push this if it's supposed to be in there already?

@Flowdalic could you have a look?

**Comment by Kev** [comment]
I don't think the assertion that this doesn't need a bump is right. Removing <private/> is an interop issue.

**Comment by Ppjet6** [comment]
Ok. If this needs another go through council I'm also fine with it. I just want to cleanup abandoned issues/PRs.

**Comment by ge0rg** [comment]
Please let me clarify. The **clarification** about the state of Carbons post-resumption does not need a bump. The replacement of `private` with `no-copy` does need a bump indeed, but it was only added into the PR because of the clarification's perceived need for the bump. Therefore, this PR must not be accepted as is, but if it is reduced to just the clarification, I'm sure it can be accepted as purely editorial.

**Comment by lnjX** [comment]
@Flowdalic Is the clarification on this still needed? If so could you rebase the changes, so we can get the pull-request done. :)

**Comment by Kev** [comment]
No activity in four years.

**Pull request closed without merging**
