### PR TITLE
XEP-0233: Include support for Microsoft SSPI in xep-0233

### PR DESCRIPTION
**Pull request by mvisode**

### CODE REVIEW

**Comment by linuxwolf** [comment]
(as co-author) these changes look fine to me.

(as editor) this update will be a new minor revision.  @mvisode is there a full name we can credit with the changes, or better yet make a co-author? (-:

**Comment by linuxwolf** [comment]
Merged as bee05d6.

**Comment by mvisode** [comment]
Saw the comments too late. But I see you have put my full name now.. :) Don't mind being a co-author - but maybe leave that for the next update now.

**Comment by linuxwolf** [comment]
I'll keep that in mind.  Don't be surprised if you see an editorial update that adds you! (-:

Thanks again!

**Pull request closed without merging**
