### PR TITLE
0186 probes

### PR DESCRIPTION
**Pull request by stpeter**
Addresses https://github.com/xsf/xeps/issues/109

### CODE REVIEW

**Comment by SamWhited** [comment]
Hi peter, this doesn't appear to merge cleanly (it's got a bunch of other extra stuff tacked on that I'm not sure what it is); could you rebase this onto an up-to-date copy of the master branch? If Git's not your thing, I can try to untangle it later.

**Comment by stpeter** [comment]
Let's just throw this out and I'll submit it from a branch off this repo instead of my fork, which seems to be horribly fubar.

**Comment by Flowdalic** [comment]
I'd prefer it if the source branch would be within your repo and not the XSF's.

**Comment by SamWhited** [comment]
Doesn't really matter, does it?

**Comment by Flowdalic** [comment]
Not much, but a bit.

**Comment by stpeter** [comment]
Life was so much easier when I was the only person working on XEPs. ;-)

**Pull request closed without merging**
