### PR TITLE
XEP-0060: be more consistent with reply

### PR DESCRIPTION
**Pull request by sstrigler**
It's not just more consistent but also easier to implement like this in most cases probably ;)

### CODE REVIEW

**Comment by linuxwolf** [comment]
This change will need some list discussion, should get buy-off from authors, and definitely needs council to weigh in.

**Comment by sstrigler** [comment]
Yeah, not so sure about that myself anymore. Maybe rather have a MAY there instead of a SHOULD?

**Comment by linuxwolf** [comment]
Bring it to the list! (-:

**Comment by SamWhited** [comment]
Do we know if this was ever discussed on list? Does anyone have a link to the discussion if so?

**Comment by sstrigler** [comment]
> On 20 mars 2016, at 16:12, Sam Whited <notifications@github.com> wrote:
> 
> Do we know if this was ever discussed on list? Does anyone have a link to the discussion if so?
> 
> 

Probably not, probably I didn't know immediately how to address this and than simply forgot about it.

I raised this when I was implementing it and found that the implementation had to be odd at that point. Which let me to believe there is an inconsistency in the protocol as well.

**Comment by sstrigler** [comment]
Oh well, and there it is: http://mail.jabber.org/pipermail/standards/2015-October/030422.html

**Comment by stpeter** [comment]
Now that I think about it more, this behavior can be helpful - most especially if a node allows multiple subscriptions with different 'subid' values (Section 6.1.6). So mentioning that and adding a 'subid' attribute to the example seems like a good idea. I'd be +1 at that point (kind of +0 at the moment). Thanks @sstrigler for the PR!

**Comment by ralphm** [comment]
Agreed with @stpeter.

**Comment by SamWhited** [comment]
Ping @sstrigler I'm going through the backlog and cleaning up a bit, any interest in resuming this work with @stpeter's blessing, or should I close this? Thanks!

**Comment by sstrigler** [comment]
Ah, wasn't sure how to read stpeter's response. So should I modify the PR accordingly? Will do.

**Comment by sstrigler** [comment]
Also rebased on latest from upstream master and removed accidental whitespace removals from second commit.

**Comment by SamWhited** [comment]
@sstrigler Many thanks! Let me know when this is in a state that you like and I'll solicit feedback from the authors again and then try to get this merged. Sorry for dropping the ball and not getting to it earlier.

**Comment by sstrigler** [comment]
I think it's ready to go 😹

**Comment by SamWhited** [comment]
Author comms sent. I'll get this in front of the council as soon as they both approve. Thanks!

**Comment by ralphm** [comment]
These changes look good to me. :shipit:

**Comment by SamWhited** [comment]
Council pinged; hopefully this will be on the agenda for next week.

**Comment by sstrigler** [comment]
Coincidentally I went over the whole XEP today and found several places where it still refers to Jabber instead of XMPP. Is this by intention or should that be fixed?

**Comment by SamWhited** [comment]
> Coincidentally I went over the whole XEP today and found several places where it still refers to Jabber instead of XMPP. Is this by intention or should that be fixed?

I think that would be a worthwhile fix; feel free to lump it in with these changes or submit a second PR if you prefer.

**Comment by ralphm** [comment]
@sstrigler so I see. Please resolve those in a different PR, except for *Jabber ID*.

**Comment by sstrigler** [comment]
I'll do another one. But not before Monday.

**Comment by SamWhited** [comment]
> I'll do another one. But not before Monday.

No rush, this is editorial so we won't need to pester the council for another review before merging, I'll just wait and lump them both into a single revision. Thanks again!

**Comment by stpeter** [comment]
LGTM!

**Pull request merged**
