### PR TITLE
XEP-0313: new revision 0.7

### PR DESCRIPTION
**Pull request by mwild1**
PR 3 of 3 for XEP-0313 0.7

Due to the well-established nature of this protocol at this point in time, I will be seeking feedback on list before considering this PR ok to merge.

### CODE REVIEW

**Comment by Ppjet6** [comment]
I'll add "Needs Author" so that we know. Ping us when you want to merge

**Comment by mwild1** [comment]
Editors, I consider this (and the two related PRs) ready to merge!

**Comment by mwild1** [comment]
Actually I've now had enough feedback that I would rather continue working on some more changes first.

**Comment by mwild1** [comment]
Having incorporated the bit of feedback from the list, I now consider this ready to merge.

**Pull request merged**
