### PR TITLE
XEP-0215: Try resolving some ambiguities

### PR DESCRIPTION
**Pull request by legastero**
- Adds attributes indicating that credentials are required (if they are not already provided)
- Adds attribute indicating when credentials expire
- Clarifies which attributes are needed to identify a service when requesting credentials

### CODE REVIEW

**Comment by SamWhited** [comment]
"Try resolving some ambiguities" is itself a bit ambiguous. Could you please provide a description which summarizes what was changed / fixed with this PR? Just a short list of bullets should suffice; nothing onerous.

Thanks!

**Comment by linuxwolf** [comment]
A note has been sent to the authors asking about these changes.

**Comment by stpeter** [comment]
With my author hat on, I'd say this looks good. IMHO adding the 'action' attribute necessitates incrementing of the protocol version. Also these changes are substantive enough that I think it would be appropriate to add Lance as a co-author.

**Comment by stpeter** [comment]
@legastero Would you mind making the changes outlined above? (Bump the protocol version and add yourself as an author.)

**Comment by linuxwolf** [comment]
Merged as 11cba41.

**Pull request closed without merging**
