### PR TITLE
edits to address feedback from JC Brand; add PSA as co-author

### PR DESCRIPTION
**Pull request by stpeter**

### CODE REVIEW

**Review by dwd — APPROVED** [review]

**Comment by stpeter** [comment]
Seeing no further comments from Board, I'll merge this PR so that we can move ahead with the Last Call.

**Comment by Kev** [comment]
> Seeing no further comments from Board, I'll merge this PR so that we can move ahead with the Last Call.

Please merge anything yet, unless you're running the scripts to do announcements etc. I'm only on holiday another couple of days and then I'll sort the backlog.

**Comment by Kev** [comment]
Ah, too late.

**Comment by stpeter** [comment]
Sorry! Should I back this out or move forward with running scripts etc.?

**Comment by Kev** [comment]
We'll cope :) As long as I remember to back it out locally next time I run the scripts it'll be ok - although I'm happy for you to do so. Let me know if you want to run them, else I'll try to remember when I'm catching up in a couple of days. 
(And yes, this is an argument for all the scripting being automatic)

**Comment by stpeter** [comment]
Sorry to be such a pain. Let me know if I can help in any way. You figure at this point in life I might actually RTFM once in a while...

**Pull request merged**
