### PR TITLE
XEP-0060: Release version 1.26.0

### PR DESCRIPTION
**Pull request by melvo**
Fix and add examples for publishing items:

* Remove 'item' element specifying its ID from example response for publishing item with ID
* Add examples for publishing item without ID

### CODE REVIEW

**Comment by melvo** [comment]
@Kev Does that bug fix release really needs the council? If so, when will they decide on it?

**Comment by Kev** [comment]
By definition a bug fix is a substantive change, which means it needs Council, yes, sorry. Will poke again.

**Comment by iNPUTmice** [comment]
Council has approved this PR under the condition that the change log gets changed to
> Add examples for publishing item without ID

**Comment by melvo** [comment]
@Kev @iNPUTmice Thanks for the feedback. It should be ready to be merged now.

**Comment by Kev** [comment]
This isn't an editorial change, so it should advance x.Y.z instead of x.y.Z.

**Pull request merged**
